
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('MOCK TITLE', 'electronics', 120000, 'July 1st 2016', 'July 31 2016' );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('MOCK TITLE', 'electronics', 120000, 'July 1st 2016', 'July 31 2016' );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('MOCK TITLE', 'electronics', 120000, 'July 1st 2016', 'July 31 2016' );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('MOCK TITLE', 'electronics', 120000, 'July 1st 2016', 'July 31 2016' );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('MOCK TITLE', 'electronics', 120000, 'July 1st 2016', 'July 31 2016' );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('MOCK TITLE', 'electronics', 120000, 'July 1st 2016', 'July 31 2016' );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('MOCK TITLE', 'electronics', 120000, 'July 1st 2016', 'July 31 2016' );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('MOCK TITLE', 'electronics', 120000, 'July 1st 2016', 'July 31 2016' );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('MOCK TITLE', 'electronics', 120000, 'July 1st 2016', 'July 31 2016' );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('MOCK TITLE', 'electronics', 120000, 'July 1st 2016', 'July 31 2016' );

INSERT INTO users (name, age) VALUES ('bob', 40);
INSERT INTO users (name, age) VALUES ('bob', 40);
INSERT INTO users (name, age) VALUES ('bob', 40);
INSERT INTO users (name, age) VALUES ('bob', 40);
INSERT INTO users (name, age) VALUES ('bob', 40);
INSERT INTO users (name, age) VALUES ('bob', 40);
INSERT INTO users (name, age) VALUES ('bob', 40);
INSERT INTO users (name, age) VALUES ('bob', 40);
INSERT INTO users (name, age) VALUES ('bob', 40);
INSERT INTO users (name, age) VALUES ('bob', 40);
INSERT INTO users (name, age) VALUES ('bob', 40);
INSERT INTO users (name, age) VALUES ('bob', 40);
INSERT INTO users (name, age) VALUES ('bob', 40);
INSERT INTO users (name, age) VALUES ('bob', 40);
INSERT INTO users (name, age) VALUES ('bob', 40);
INSERT INTO users (name, age) VALUES ('bob', 40);
INSERT INTO users (name, age) VALUES ('bob', 40);
INSERT INTO users (name, age) VALUES ('bob', 40);
INSERT INTO users (name, age) VALUES ('bob', 40);
INSERT INTO users (name, age) VALUES ('bob', 40);

INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
